rm(list = setdiff(ls(), lsf.str()))
library(pheatmap)
library(data.table)
library(tibble)
library(dplyr)
library(RColorBrewer)
library(dendsort)
library(emdbook)
library(seriation)
library(ggplot2)
library(ggdendro)
library(vegan)
library(dplyr)
library(dendextend)
library(DendSer)

d<-fread('matrixnormmetalpha0.5newmethodmarinephantome.csv',data.table = FALSE)
d<-d%>%column_to_rownames('met')
c<- as.matrix(d)
sort_hclust <- function(...) as.hclust(dendsort(as.dendrogram(...),type='min'))

#mcc <- sort_hclust(hclust(dist(t(c)),method='complete'))
#mcr <-sort_hclust(hclust(dist(c),method='complete'))

e1<-dendsort(as.dendrogram(hclust(vegdist(t(c), method="bray"),method = 'average')))
e2<-dendsort(as.dendrogram(hclust(vegdist(c, method="bray"),method = 'average')))

anu<-as.hclust(e1%>%ladderize)
anu2<-as.hclust(e2%>%ladderize)
breaklist=lseq(min(c[c>0]),max(c),length.out = 100)

tiff("sinnormgen_matrizalpha0.5phantomemarine.tiff", units='cm',width = 25, height = 20, res=600)
Q<-pheatmap(mat=c, show_colnames = T,fontsize_row =3,treeheight_row = 100,treeheight_col = 100,fontsize_col = 3,cluster_cols = anu,cluster_rows =anu2,breaks = breaklist,color=colorRampPalette(c('blue','green','yellow','orange','red'))(length(breaklist)))
dev.off()